import type {INews} from "./interfaces.ts";

export const mockNews: INews[] = [
    {
        ticker: 'SBER',
        source: 'https://finance.example.com/news/sber-1',
        summary_text: 'Сбербанк увеличил кредитный портфель на 10%.',
        price_difference: '+3.5%',
        is_green: true,
        description: 'Подробный отчет по росту кредитного портфеля Сбербанка.',
        timestamp: '2025-06-17T08:00:00Z',
    },
    {
        ticker: 'GAZP',
        source: 'https://energy.example.com/news/gazp-1',
        summary_text: 'Газпром планирует увеличить экспорт газа в Европу.',
        price_difference: '+1.2%',
        is_green: true,
        description: 'Информация о планах Газпрома по экспорту газа в 2025 году.',
        timestamp: '2025-06-16T12:30:00Z',
    },
    {
        ticker: 'LKOH',
        source: 'https://oil.example.com/news/lkoh-1',
        summary_text: 'Лукойл столкнулся с проблемами в производстве нефти.',
        price_difference: '-2.0%',
        is_green: false,
        description: 'Причины снижения производства нефти на предприятиях Лукойла.',
        timestamp: '2025-06-15T14:45:00Z',
    },
    {
        ticker: 'SBER',
        source: 'https://finance.example.com/news/sber-2',
        summary_text: 'Сбербанк внедряет новые цифровые сервисы для клиентов.',
        price_difference: '+0.5%',
        is_green: true,
        description: 'Описание новых цифровых продуктов Сбербанка.',
        timestamp: '2025-06-14T09:20:00Z',
    },
    {
        ticker: 'YNDX',
        source: 'https://tech.example.com/news/yndx-1',
        summary_text: 'Яндекс запустил новый сервис онлайн-обучения.',
        price_difference: '+4.0%',
        is_green: true,
        description: 'Информация о запуске нового сервиса от Яндекса.',
        timestamp: '2025-06-13T16:10:00Z',
    },
    {
        ticker: 'GAZP',
        source: 'https://energy.example.com/news/gazp-2',
        summary_text: 'Газпром столкнулся с сокращением поставок в некоторые регионы.',
        price_difference: '-1.5%',
        is_green: false,
        description: 'Причины и последствия сокращения поставок Газпрома.',
        timestamp: '2025-06-12T10:00:00Z',
    },
    {
        ticker: 'SBER',
        source: 'https://finance.example.com/news/sber-3',
        summary_text: 'Сбербанк расширяет сеть банкоматов в регионах.',
        price_difference: '+1.1%',
        is_green: true,
        description: 'Планы Сбербанка по расширению инфраструктуры.',
        timestamp: '2025-06-11T11:30:00Z',
    },
    {
        ticker: 'LKOH',
        source: 'https://oil.example.com/news/lkoh-2',
        summary_text: 'Лукойл инвестирует в возобновляемую энергетику.',
        price_difference: '+2.3%',
        is_green: true,
        description: 'Стратегия Лукойла по диверсификации энергетического портфеля.',
        timestamp: '2025-06-10T13:00:00Z',
    },
    {
        ticker: 'YNDX',
        source: 'https://tech.example.com/news/yndx-2',
        summary_text: 'Яндекс увеличил выручку в первом квартале.',
        price_difference: '+5.0%',
        is_green: true,
        description: 'Анализ финансовых результатов Яндекса за квартал.',
        timestamp: '2025-06-09T15:45:00Z',
    },
    {
        ticker: 'GAZP',
        source: 'https://energy.example.com/news/gazp-3',
        summary_text: 'Газпром ведет переговоры о новых контрактах с Китаем.',
        price_difference: '+3.0%',
        is_green: true,
        description: 'Детали переговоров Газпрома и китайских партнеров.',
        timestamp: '2025-06-08T09:15:00Z',
    },
];
